// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameCip = "cips"

// Cip mapped from table <cips>
type Cip struct {
	ID          int32   `gorm:"column:id;type:int;primaryKey;autoIncrement:true;uniqueIndex:id_UNIQUE_CIP,priority:1" json:"id"`
	Cip         float64 `gorm:"column:cip;type:decimal(7,5);not null;uniqueIndex:cip_UNIQUE,priority:1" json:"cip"`
	Name        string  `gorm:"column:name;type:varchar(45);not null" json:"name"`
	Description string  `gorm:"column:description;type:varchar(200);not null" json:"description"`
	Jobs        string  `gorm:"column:jobs;type:varchar(150);not null" json:"jobs"`
}

// TableName Cip's table name
func (*Cip) TableName() string {
	return TableNameCip
}