// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameGradLevel = "grad_levels"

// GradLevel mapped from table <grad_levels>
type GradLevel struct {
	ID    int32   `gorm:"column:id;type:int;primaryKey;autoIncrement:true;uniqueIndex:id_UNIQUE_LEVEL,priority:1" json:"id"`
	Level *string `gorm:"column:level;type:varchar(20)" json:"level"`
}

// TableName GradLevel's table name
func (*GradLevel) TableName() string {
	return TableNameGradLevel
}