// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameMajor = "majors"

// Major mapped from table <majors>
type Major struct {
	ID     int32   `gorm:"column:id;type:int;primaryKey;autoIncrement:true;uniqueIndex:id_UNIQUE_MAJOR,priority:1" json:"id"`
	Code string `gorm:"column:code;type:varchar(8)" json:"code"`
	Name string `gorm:"column:name;type:varchar(35)" json:"name"`
}

// TableName Major's table name
func (*Major) TableName() string {
	return TableNameMajor
}