// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameProgram = "programs"

// Program mapped from table <programs>
type Program struct {
	ID          int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true;" json:"id"`
	Name        string `gorm:"column:name;type:varchar(100);not null" json:"name"`
    GradLevelID int32     `gorm:"column:grad_level;type:int;not null;index:grad_level_idx,priority:1" json:"-"`
	GradLevel   GradLevel `gorm:"foreignKey:GradLevelID" json:"grad_level"`
	ProgramType string `gorm:"column:program_type;type:varchar(45);not null" json:"program_type"`
    SchoolID    int32     `gorm:"column:school;type:int;not null" json:"-"`
    School      School    `gorm:"foreignKey:SchoolID;" json:"school"`
	MajorCode   string `gorm:"column:major_code;type:varchar(10);not null" json:"major_code"`
	Online      int8  `gorm:"column:online;type:tinyint;not null" json:"online"`
	Campus      int8  `gorm:"column:campus;type:tinyint;not null" json:"campus"`
	Description string `gorm:"column:description;type:text;not null" json:"description"`
	Cip         int32  `gorm:"column:cip;type:int;not null;index:cip_idx,priority:1" json:"cip"`
	CreatedBy   int32  `gorm:"column:created_by;type:int;not null" json:"created_by"`
}

// TableName Program's table name
func (*Program) TableName() string {
	return TableNameProgram
}