// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSchool = "schools"

// School mapped from table <schools>
type School struct {
	ID   int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Code string `gorm:"column:code;type:varchar(5);not null" json:"code"`
	Name string `gorm:"column:name;type:varchar(100);not null" json:"name"`
}

// TableName School's table name
func (*School) TableName() string {
	return TableNameSchool
}