// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID       int32  `gorm:"column:id;type:int;primaryKey;autoIncrement:true;uniqueIndex:id_UNIQUE_USER,priority:1" json:"id"`
	Username string `gorm:"column:username;type:varchar(45);not null" json:"username"`
	Roles    string `gorm:"column:roles;type:varchar(150);not null" json:"roles"`
	ClientID int32  `gorm:"column:client_id;type:int;not null;,priority:1" json:"client_id"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}